### PR TITLE
Use @octokit/graphql instead of own bindings

### PR DESCRIPTION
**Pull request by foolip**
This means a bit less code to maintain, and the ability to use GraphQL
variables.

lib/graphql.js is kept around to make it easier to mock out including
the config in other tests.

Also normalize the indentation of the GraphQL query blocks.

### CODE REVIEW

**Comment by foolip** [comment]
https://github.com/w3c/validate-repos/pull/77/checks?check_run_id=347218592 hit rate limits, and I don't know if that's because of these changes or just because I pushed the branch twice. It will be best to wait for a while and trigger again.

I also want to look at fetching more labels at once to use fewer requests and make the validate step faster.

**Comment by foolip** [comment]
I've sent https://github.com/w3c/validate-repos/pull/78, it would be a good idea to land that first, then I can rebase this and have higher confidence that it still works.

**Comment by foolip** [comment]
Ugh, "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again"

Most of the requests are because we're paginating labels in too small chunks. Since we're fetching all of them unconditionally, I'll try to fix that too here...

**Comment by dontcallmedom** [comment]
for background, we came to use small batches because we would otherwise get random empty responses from github; it later appeared this was most likely because we were running parallel queries across organizations rather than too big batches, but we never got complete clarity on this.

(in any case, +1 to experimenting with that)

**Comment by foolip** [comment]
Interesting, that might just be what I'm hitting again! Right now there's actually still up to 10 parallel requests when fetching labels. I'll try to rejig things to never request in parallel, but request as much as possible each time. Only 3 repos have >100 labels, so this should greatly reduce the number of requests.

**Comment by foolip** [comment]
Trying to solve the quote problem led to a different approach, closing this in favor of https://github.com/w3c/validate-repos/pull/79.

**Pull request closed without merging**
