### PR TITLE
Run validate.js on GitHub Actions

### PR DESCRIPTION
**Pull request by foolip**
This doesn't yet deploy the resulting report.json anywhere.

### CODE REVIEW

**Comment by foolip** [comment]
@dontcallmedom for this to actually work you'd need to add two secrets to this repo. https://github.com/foolip/validate-repos/runs/299111603 shows what this will do if merged, but my own access token doesn't have the right permissions to the w3c org and so doesn't produce the right output.

**Comment by dontcallmedom** [comment]
thanks a lot for this @foolip - do you have handy the command to generate the secrets for github actions? I can look it up otherwise.

**Comment by foolip** [comment]
@dontcallmedom you'll need to visit https://github.com/w3c/validate-repos/settings/secrets (404 for me,  I used https://github.com/foolip/validate-repos/settings/secrets for my experiment) and a secret named `W3C_API_KEY`, a string of length 31 in my case.

`GITHUB_TOKEN` is provided by GitHub Actions but doesn't actually work. I think it'll be necessary to use a personal access token with at least the "public_repo", "read:org" and "read:repo_hook" scopes. I'd suggest calling it something other than `GITHUB_TOKEN`, maybe naming it after the user whose token it is, or `W3C_GITHUB_TOKEN` perhaps. The `${{ secrets.GITHUB_TOKEN }}` bit in the PR then needs to be updated as well.

**Comment by dontcallmedom** [comment]
I've kept my separate cron job for now - I'll disable it once we have confirmation this is working as expected. Thanks a lot for pushing this!

**Comment by foolip** [comment]
Exciting, it's running in https://github.com/w3c/validate-repos/runs/299359501 now.

**Comment by dontcallmedom** [comment]
looking good :)

**Comment by foolip** [comment]
It's finished now and it looks like there were two interesting differences. I can't tell if that's because things have really changed since it was last run though. @dontcallmedom can you?

**Comment by dontcallmedom** [comment]
is the process supposed to update report.json in the repo? it didn't seem to do that.

I checked the diff, and it at least matches the reality of the repo (so likely reflects changes brought the past 24 hours)

**Comment by foolip** [comment]
No, I didn't add the step to actually push the changes and just do `git diff` until it's clear that this is working.

If you think the output looks correct, I'll set up the final bit to push the changes.

**Comment by dontcallmedom** [comment]
yes, the diff looks correct - thanks for pushing the final bits then :)

**Comment by foolip** [comment]
I've sent https://github.com/w3c/validate-repos/pull/40.

**Pull request merged**
