### PR TITLE
Remove some unused variables

### PR DESCRIPTION
**Pull request by foolip**
Found by running ESLint.

### CODE REVIEW

**Comment by foolip** [comment]
@dontcallmedom if you'd like I can submit the ESLint config too. It's catching some mistakes but also would add a maintenance burden so I'm not sure what the right tradeoff is.

**Comment by dontcallmedom** [comment]
I'm happy to have ESLint brought in as well

**Comment by foolip** [comment]
@dontcallmedom alright, I'll send that separately.

**Comment by foolip** [comment]
But I think I'll wait until after https://github.com/w3c/validate-repos/pull/38 so I can enable it in CI at the same time.

**Comment by foolip** [comment]
Actually, no, a separate workflow for that would be OK, so I'll do it in parallel.

**Pull request merged**
